"""Validates translated chunks and writes Polyglot language files.

Usage: python tools/corpus/merge_translations.py ru [de fr ...]   (no args = every folder in corpus/tr)

Reads   corpus/source.jsonl + corpus/tr/<lang>/NN.jsonl ({"id", "t"})
Writes  mods/Polyglot/languages/<lang>.txt       valid entries, Polyglot format
        corpus/tr/<lang>/_issues.jsonl            rejected / missing entries (to re-translate)
"""
import collections
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
PLACEHOLDER = re.compile(r"<[A-Z][A-Z0-9_]*>|<Input_[A-Za-z0-9]+>|\{\d+\}")
TAG = re.compile(r"</?[a-zA-Z][^<>]*>")
# Early corpus builds normalized already-normalized miss-log texts twice ("{0}" -> "{{0}}").
DOUBLE_SLOT = re.compile(r"\{\{(\d+)\}\}")
LANGS = {
    "ru": ("Русский", "Russian", "Cyrillic"), "uk": ("Українська", "Ukrainian", "Cyrillic"),
    "de": ("Deutsch", "German", "Latin"), "fr": ("Français", "French", "Latin"), "es": ("Español", "Spanish", "Latin"),
    "pt-BR": ("Português (Brasil)", "Portuguese (Brazil)", "Latin"), "it": ("Italiano", "Italian", "Latin"),
    "pl": ("Polski", "Polish", "Latin"), "tr": ("Türkçe", "Turkish", "Latin"),
    "zh-CN": ("简体中文", "Chinese (Simplified)", "ChineseSimplified"), "ja": ("日本語", "Japanese", "Japanese"),
    "ko": ("한국어", "Korean", "Korean"),
}


def escape(s: str, key: bool) -> str:
    s = s.replace("\\", "\\\\").replace("\n", "\\n").replace("\r", "\\r").replace("\t", "\\t")
    return s.replace("=", "\\=") if key else s


def edge_ws(s: str):
    return s[: len(s) - len(s.lstrip())], s[len(s.rstrip()):]


def problems(key: str, t: str) -> list:
    out = []
    if not t or not t.strip():
        return ["empty"]
    if collections.Counter(PLACEHOLDER.findall(key)) != collections.Counter(PLACEHOLDER.findall(t)):
        out.append("placeholders")
    key_tags = collections.Counter(x for x in TAG.findall(key) if not PLACEHOLDER.fullmatch(x))
    t_tags = collections.Counter(x for x in TAG.findall(t) if not PLACEHOLDER.fullmatch(x))
    if key_tags != t_tags:
        out.append("tags")
    if key.count("\n") != t.count("\n"):
        out.append("newlines")
    if edge_ws(key) != edge_ws(t):
        out.append("edge-whitespace")
    return out


def merge(lang: str) -> None:
    source = [json.loads(line)["key"] for line in open(ROOT / "corpus" / "source.jsonl", encoding="utf-8")]
    folder = ROOT / "corpus" / "tr" / lang
    translated = {}
    for path in sorted(folder.glob("[0-9]*.jsonl")):
        for n, line in enumerate(open(path, encoding="utf-8"), 1):
            line = line.strip()
            if not line:
                continue
            try:
                row = json.loads(line)
                translated[int(row["id"])] = row["t"]
            except (ValueError, KeyError) as ex:
                print(f"  {path.name}:{n}: bad line ({ex})")

    good, issues = [], []
    for i, key in enumerate(source):
        t = translated.get(i)
        if t is None:
            issues.append({"id": i, "key": key, "problems": ["missing"]})
            continue
        found = problems(key, t)
        if found:
            issues.append({"id": i, "key": key, "t": t, "problems": found})
        else:
            good.append((key, t))

    name, english, script = LANGS.get(lang, (lang, lang, "Latin"))
    out = ROOT / "mods" / "Polyglot" / "languages" / f"{lang}.txt"
    with out.open("w", encoding="utf-8", newline="\n") as f:
        f.write(f"// Polyglot translation: {english}. Generated by tools/corpus/merge_translations.py\n")
        f.write(f"@name={name}\n@english={english}\n@script={script}\n")
        for key, t in good:
            key, t = DOUBLE_SLOT.sub(r"{\1}", key), DOUBLE_SLOT.sub(r"{\1}", t)
            f.write(f"{escape(key, True)}={escape(t, False)}\n")
    with (folder / "_issues.jsonl").open("w", encoding="utf-8") as f:
        for issue in issues:
            f.write(json.dumps(issue, ensure_ascii=False) + "\n")
    kinds = collections.Counter(p for x in issues for p in x["problems"])
    print(f"{lang}: {len(good)}/{len(source)} ok, {len(issues)} issues {dict(kinds)} -> {out.name}")


def main() -> None:
    langs = sys.argv[1:] or sorted(p.name for p in (ROOT / "corpus" / "tr").iterdir() if p.is_dir())
    for lang in langs:
        merge(lang)


if __name__ == "__main__":
    main()
